### PR TITLE
Updating remaining tasks count in App.js

### PR DESCRIPTION
**Pull request by akash-more**
Remaining tasks should show how many tasks are remaining to be completed

### CODE REVIEW

**Comment by toddrgarner** [comment]
approved

**Comment by bsmth** [comment]
Hi @akash-more, thanks for the submission. There's some conflicts that need to be fixed; would you like to resolve them?

**Comment by akash-more** [comment]
Sure, will do it @bsmth.

**Comment by bsmth** [comment]
Thanks a lot for opening this one. After coming back to it, I'm going to close the pull request for now. The changes are a nice improvement, but we're not going to continue adding to the functionality of the demo as this will become harder to maintain and keep in sync with the content repository / guides - the scope of the demo will keep growing. Thanks for your understanding :)

**Pull request closed without merging**
