### PR TITLE
Fix: fix submitting empty todo

### PR DESCRIPTION
**Pull request by ppalone**
Currently, a to do can be added even if it is empty. Also, while editing a to do it can be saved even if it is empty. This PR will fix the above two issues.
Also thanks team MDN for great resources on web development.

### CODE REVIEW

**Comment by ppalone** [comment]
I made the changes. Also thanks to @peterbe.

**Comment by RafaelGreen1** [comment]
I'm not sure if it's user friendly to just do nothing when user clicks a button (I would at least notify her that empty task is not allowed or something like that)

**Comment by chrisdavidmills** [comment]
Tested it, looks good. Thanks!

**Comment by ppalone** [comment]
Thanks @chrisdavidmills

**Comment by peterbe** [comment]
What I usually do is a pattern of not even having to confront the problem. I.e. something like this:

```javascript
function MyApp() {
  const [name, setName] = useState('');
  
  return <form onSubmit={event => {
    event.preventDefault();
    if (!name.trim()) {
       throw new Error("name empty")  
    }
    addName(name)
  }}>
  <input type="text" value="name" onChange={event => setName(event.target.value)}/>
  <button type="submit" disabled={!name.trim()}>Submit</button>
  </form>
}
```
That way, you can't even press the Submit button until there's something typed there. 

That's just sample code but it's a good pattern.

**Pull request merged**
